apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
  bootstrap:
    initdb:
      database: n8n
      owner: n8n
  postgresql:
    parameters:
      max_connections: "100"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
